### PR TITLE
Bam 24 project overview component

### PR DESCRIPTION
**Pull request by michael-staples**
- Added ProjectProfile component to enable detailed viewing and editing/deletion of project information.
- Integrated API calls within ProjectProfile to fetch, display, and update project details based on the project ID from the URL parameters.
- Updated ProjectList to include direct links to the ProjectProfile.
- Updated Project Schema/Model.

### CODE REVIEW

**Review by simpsbri — DISMISSED** [review]
Additional updates made to address new path/component passing due to private routes. And to address several merge conflict issues.

**Review by adannavejas — DISMISSED** [review]
lgtm

**Review by simpsbri — APPROVED** [review]
Review #2 lgtm

**Review by simpsbri — APPROVED** [review]
lgtm

**Pull request merged**
