### PR TITLE
Bam 30 move project list to own component and out of main

### PR DESCRIPTION
**Pull request by simpsbri**
Moved the Project List and Project Card to it's own component and out of the Main component.

### CODE REVIEW

**Comment by adannavejas** [comment]
> Moved the Project List and Project Card to it's own component and out of the Main component.

AHHH, I see you answered my question here!

**Review by adannavejas — DISMISSED** [review]
Looks good to me! 👌

**Review by adannavejas — DISMISSED** [review]
Reapproving this beacuse code base changed: The merge-base changed after approval.

**Comment by adannavejas** [comment]
Second approval failed, looks like we need @michael-staples appproval 🤔

**Comment by simpsbri** [comment]
> Second approval failed, looks like we need @michael-staples appproval 🤔

@adannavejas I added a re-request for review?

**Review by adannavejas — DISMISSED** [review]
Looks good, plz work 🫠

**Comment by adannavejas** [comment]
@simpsbri we may need to revist the rules? https://github.com/simpsbri/ptsb-oct-23-capstone-team-1/rules?ref=refs%2Fheads%2Fmain, Not sure why its not taking in my approval

**Review by michael-staples — DISMISSED** [review]
LGTM

**Pull request closed without merging**
